---
- hosts: localhost
  gather_facts: no
  vars_files:
   - "vars/tenant.yml"
  vars:
    # VPC,Subnet,Secgroup,ECS,EIP
    image_name: "{{ vms[ecs_name].image_name | default(default.image_name) }}"
    availability_zone: "{{ vms[ecs_name].availability_zone | default(default.availability_zone) }}"
    vpc_name: "{{ vms[ecs_name].vpc_name  }}"
    vpc_net: "{{ vms[ecs_name].vpc_net  }}"
    subnet_name: "{{ vms[ecs_name].subnet_name | default(default.subnet_name) }}"
    subnet_net: "{{ vms[ecs_name].subnet_net | default(default.subnet_net) }}"
    subnet_gateway: "{{ vms[ecs_name].subnet_gateway | default(default.subnet_gateway) }}"
    subnet_dhcp_enable: "{{ vms[ecs_name].subnet_dhcp_enable | default(default.subnet_dhcp_enable) }}"
    subnet_primary_dns: "{{ vms[ecs_name].subnet_primary_dns | default(default.subnet_primary_dns) }}"
    subnet_secondary_dns: "{{ vms[ecs_name].subnet_secondary_dns | default(default.subnet_secondary_dns) }}"
    secgroups: "{{ vms[ecs_name].secgroups | default(default.secgroups) }}"
    secgrouprules: "{{ securitygroups[secgroup_name] }}"
    # ecs_ipaddress: "{{ vms[ecs_name].ecs_ipaddress | default(default.ecs_ipaddress) }}"
    public_ip_address: "{{ vms[ecs_name].ecs_publicip }}"
    ptr_name: "{{ vms[ecs_name].ecs_publicfqdn }}"
    eip_bandwidth_name: "{{ vms[ecs_name].eip_bandwidth_name | default(default.eip_bandwidth_name) }}"
    eip_bandwidth_size: "{{ vms[ecs_name].eip_bandwidth_size | default(default.eip_bandwidth_size) }}"
    ecs_volumetype: "{{ vms[ecs_name].ecs_volumetype | default(default.ecs_volumetype) }}"
    ecs_volumesize: "{{ vms[ecs_name].ecs_volumesize | default(default.ecs_volumesize) }}"
    ecs_ram: "{{ vms[ecs_name].ecs_ram | default(default.ecs_ram) }}"
    ecs_vcpus: "{{ vms[ecs_name].ecs_vcpus | default(default.ecs_vcpus) }}"
    ecs_adminkey: "{{ vms[ecs_name].ecs_adminkey | default(default.ecs_adminkey) }}"
    keypair_file: "{{ vms[ecs_name].keypair_file | default(default.keypair_file) }}"
    # EVS
    evs_availability_zone: "{{ volumes[evs_name].evs_availability_zone | default(default.evs_availability_zone) }}"
    evs_volume_type: "{{ volumes[evs_name].evs_volume_type | default(default.evs_volume_type) }}"
    evs_size: "{{ volumes[evs_name].evs_size | default(default.evs_size) }}"
    evs_multiattach: "{{ volumes[evs_name].evs_multiattach | default(default.evs_multiattach) }}"
    evs_scsi: "{{ volumes[evs_name].evs_scsi | default(default.evs_scsi) }}"
    # playbook action
    localaction: "delete"

  roles:
    # create VM
    - role: "otc_auth"
    - role: "otc_ecs"
    - role: "otc_eip"
    - role: "otc_keypair"
    - role: "otc_secgroup"
    - role: "otc_subnet"
    - role: "otc_vpc"
